sudo: required
dist: xenial
install: git clone https://github.com/QubesOS/qubes-builder ~/qubes-builder
before_script:
 - export GNUPGHOME=~/qubes-builder/keyrings/git
 - mkdir --parents "$GNUPGHOME"
 - chmod --recursive 700 "$GNUPGHOME"
 - gpg --import ~/qubes-builder/qubes-developers-keys.asc
 - echo '427F11FD0FAA4B080123F01CDDFA1A3E36879494:6:' | gpg --import-ownertrust
 - gpg --keyserver keys.gnupg.net --recv-keys "9FA64B92F95E706BF28E2CA6484010B5CDC576E2"
 - gpg --fingerprint "9FA64B92F95E706BF28E2CA6484010B5CDC576E2"
 - echo '9FA64B92F95E706BF28E2CA6484010B5CDC576E2:6:' | gpg --import-ownertrust
 - gpg --fingerprint "9FA64B92F95E706BF28E2CA6484010B5CDC576E2"
 - export VERBOSE=3
 - export DEBUG=1
 - export CHECK_BRANCH=1
 - export BRANCH_template_kali=master
 - export GIT_URL_template_kali=https://github.com/fepitre/qubes-template-kali.git
 - export BUILDER_PLUGINS="template-kali builder-debian"
 - env
script: ~/qubes-builder/scripts/travis-build linux-template-builder
after_success:
 - ls -l ~/qubes-builder/qubes-src/linux-template-builder/rpm/noarch
language: generic
env:
 - DISTS_VM=kali-standard USE_QUBES_REPO_VERSION=4.0 USE_QUBES_REPO_TESTING=1
